// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateRelationship_hisstock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateRelationship_hisstock));
        
        string IMigrationMetadata.Id
        {
            get { return "201705241332459_updateRelationship_hisstock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
