// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyTable_sysDictionary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyTable_sysDictionary));
        
        string IMigrationMetadata.Id
        {
            get { return "201704061322036_modifyTable_sysDictionary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
