// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyTable_projectTask : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyTable_projectTask));

        string IMigrationMetadata.Id
        {
            get
            {
                return "201702141006501_modifyTable_projectTask";
            }
        }

        string IMigrationMetadata.Source
        {
            get
            {
                return null;
            }
        }

        string IMigrationMetadata.Target
        {
            get
            {
                return Resources.GetString("Target");
            }
        }
    }
}
