// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyTable_ApplyForVehicleMaintenance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyTable_ApplyForVehicleMaintenance));
        
        string IMigrationMetadata.Id
        {
            get { return "201708011534561_modifyTable_ApplyForVehicleMaintenance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
