// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTable_StoreStocks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTable_StoreStocks));
        
        string IMigrationMetadata.Id
        {
            get { return "201707300903359_addTable_StoreStocks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
