// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateTable_actualoutlay4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateTable_actualoutlay4));
        
        string IMigrationMetadata.Id
        {
            get { return "201704241233388_updateTable_actualoutlay4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
