// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTable_ProjectManagement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTable_ProjectManagement));
        
        string IMigrationMetadata.Id
        {
            get { return "201806191328262_addTable_ProjectManagement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
