// <auto-generated />
namespace SCBF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class miodifyTable_PerformanceAmountDetail3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(miodifyTable_PerformanceAmountDetail3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806181402359_miodifyTable_PerformanceAmountDetail3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
